favicon: null
name: JakeStromberg
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 0.5
  rhythmicContrast: 0
  brandColors:
    - '#eeede8'
    - '#b2aa9f'
    - '#412518'
    - '#695346'
    - '#df5754'
  lightness: 0.5
typography_spectrum: 0.4266105836723
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.6829787
analytics:
  twitter: null
  google: null
  facebook: null
