name: JakeStromberg
favicon: null
layout_spectrum: 0.045114123262465
typography_spectrum: 0.4266105836723
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeede8'
    - '#b2aa9f'
    - '#412518'
    - '#695346'
    - '#df5754'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5926868368405849
purpose: []
